name = "view-counter"
main = "index.js"
compatibility_date = "2025-10-12"

[[kv_namespaces]]
binding = "VIEW_COUNTS" # Worker kodunda kullanÄ±lacak isim (env.KV)
id = "13f653d049d248cba1bdba46345302b4"